name: "Build"
on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "refactor/*"
    tags:
      - "!#*"

jobs:
  build_apps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew jar
    # Executable App
    # KeySwitchManager.CLI
    - uses: actions/upload-artifact@v2
      with:
        name: jdddcommons
        path: ./build/libs/

